# Generated by Django 5.1.6 on 2025-03-10 14:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Argentina', 'Argentina'), ('Brazil', 'Brazil'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Mexico', 'Mexico'), ('Peru', 'Peru'), ('Russia', 'Russia'), ('United States', 'United States'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('Denmark', 'Denmark'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Belgium', 'Belgium'), ('Netherlands', 'Netherlands'), ('Portugal', 'Portugal'), ('Iceland', 'Iceland'), ('Philippines', 'Philippines'), ('Vietnam', 'Vietnam'), ('United Arab Emirates', 'United Arab Emirates'), ('Saudi Arabia', 'Saudi Arabia'), ('Canada', 'Canada')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='destination_image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_popular', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.country')),
            ],
        ),
    ]
