# Generated by Django 5.1.6 on 2025-03-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, help_text='Enter Tailwind CSS or SVG class for the icon', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='destination.facility'),
        ),
    ]
