# Generated by Django 5.1.4 on 2025-01-09 08:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('preferred_currency', models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('SEK', 'Swedish Krona'), ('NZD', 'New Zealand Dollar'), ('MXN', 'Mexican Peso'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar'), ('NOK', 'Norwegian Krone'), ('KRW', 'South Korean Won'), ('TRY', 'Turkish Lira'), ('INR', 'Indian Rupee'), ('RUB', 'Russian Ruble'), ('ZAR', 'South African Rand'), ('BRL', 'Brazilian Real'), ('THB', 'Thai Baht'), ('MYR', 'Malaysian Ringgit'), ('IDR', 'Indonesian Rupiah'), ('PHP', 'Philippine Peso'), ('VND', 'Vietnamese Dong'), ('ILS', 'Israeli Shekel'), ('PLN', 'Polish Zloty'), ('AED', 'United Arab Emirates Dirham'), ('SAR', 'Saudi Riyal'), ('EGP', 'Egyptian Pound'), ('PKR', 'Pakistani Rupee'), ('BDT', 'Bangladeshi Taka'), ('NGN', 'Nigerian Naira'), ('KWD', 'Kuwaiti Dinar')], default='USD', max_length=10, null=True)),
                ('travel_preferences', models.CharField(blank=True, choices=[('adventure', 'Adventure'), ('relaxation', 'Relaxation'), ('culture', 'Culture'), ('nature', 'Nature'), ('luxury', 'Luxury'), ('others', 'Others')], max_length=20, null=True)),
                ('travel_frequency', models.CharField(blank=True, choices=[('frequent', 'Frequent (Monthly)'), ('occasional', 'Occasional (Quarterly)'), ('rare', 'Rare (Yearly)')], max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('favorite_destinations', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('complete_profile', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
